- hosts: all
  become: True
  tasks:
    - name: install redis
      apt:
        name: redis
        state: present
    - name: shutdown redis service
      service:
        name: redis
        state: stopped
    - name: copy redis config
      copy:
        src: redis.conf
        dest: /etc/redis/redis.conf
        owner: root
        group: redis
        mode: 0660
    - name: shutdown redis service
      service:
        name: redis
        state: started    